xcopy %PathES%*tes*.js %PathApp% /Y /D:%1
xcopy %PathES%*wes*.js %PathApp% /Y /D:%1
xcopy %PathES%ares*.js %PathApp% /Y /D:%1
xcopy %PathES%*tco*.js %PathApp% /Y /D:%1
xcopy %PathES%*wco*.js %PathApp% /Y /D:%1
xcopy %PathES%*rco*.js %PathApp% /Y /D:%1
xcopy %PathES%*tft*.js %PathApp% /Y /D:%1
xcopy %PathES%*wft*.js %PathApp% /Y /D:%1
xcopy %PathES%*rft*.js %PathApp% /Y /D:%1
xcopy %PathES%*tpq*.js %PathApp% /Y /D:%1
xcopy %PathES%*wpq*.js %PathApp% /Y /D:%1
xcopy %PathES%*rpq*.js %PathApp% /Y /D:%1
xcopy %PathES%*ram*.js %PathApp% /Y /D:%1
xcopy %PathES%*tam*.js %PathApp% /Y /D:%1
xcopy %PathES%*wam*.js %PathApp% /Y /D:%1

xcopy %PathES%bin\*pes* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*tes* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*wes* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\ares* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\apwses* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\pco*  %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\apco*  %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*tco* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*wco* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*rco* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\apwsco* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*tft* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*wft* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*rft* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*pft* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\apwsft* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*tpq* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*wpq* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*rpq* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*ppq* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*tam* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*wam* %PathApp%\bin /Y /D:%1
xcopy %PathES%bin\*ram* %PathApp%\bin /Y /D:%1 /EXCLUDE:GeneXus.Programs.Common.dll