xcopy %PathFP%*tfp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*wfp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*rfp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*pfp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*trh*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*wrh*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*rrh*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*prh*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*tdp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*wdp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*rdp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*pdp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*tpe*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*wpe*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*rpe*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*ppe*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*tpp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*wpp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*rpp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*ppp*.js %PathApp% /D:%1 /Y

xcopy %PathFP%*tgp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*wgp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*rgp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*pgp*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*tst*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*wst*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*rst*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*pst*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*tmd*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*wmd*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*rmd*.js %PathApp% /D:%1 /Y
xcopy %PathFP%*pmd*.js %PathApp% /D:%1 /Y

cd bin
xcopy %PathFP%bin\*tfp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wfp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wsfp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*rfp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*pfp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*trh* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wrh* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wsrh* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*rrh* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*prh* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*tdp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wdp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wsdp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*rdp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*pdp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*tpe* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wpe* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wspe* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*rpe* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*ppe* %PathApp%\bin /D:%1 /Y

xcopy %PathFP%bin\*tpp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wpp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wspp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*rpp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*ppp* %PathApp%\bin /D:%1 /Y

xcopy %PathFP%bin\*tgp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wgp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wsgp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*rgp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*pgp* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*tst* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wst* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wsst* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*rst* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*pst* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*tmd* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wmd* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*wsmd* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*rmd* %PathApp%\bin /D:%1 /Y
xcopy %PathFP%bin\*pmd* %PathApp%\bin /D:%1 /Y