xcopy %PathPC%*tpc*.js %PathApp% /D:%1 /Y
xcopy %PathPC%*wpc*.js %PathApp% /D:%1 /Y
xcopy %PathPC%*rpc*.js %PathApp% /D:%1 /Y
xcopy %PathPC%*ppc*.js %PathApp% /D:%1 /Y
xcopy %PathPC%*tex*.js %PathApp% /D:%1 /Y
xcopy %PathPC%*wex*.js %PathApp% /D:%1 /Y
xcopy %PathPC%*rex*.js %PathApp% /D:%1 /Y
xcopy %PathPC%*pex*.js %PathApp% /D:%1 /Y

xcopy %PathPC%bin\*tpc* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*wpc* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*wspc* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*rpc* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*ppc* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*tex* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*wex* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*wsex* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*rex* %PathApp%\bin /D:%1 /Y
xcopy %PathPC%bin\*pex* %PathApp%\bin /D:%1 /Y